export const CUSTOMER_SEARCHABLE_FIELDS = ['name', 'phone', 'email'];

export const CUSTOMER_VALIDATION = {
  NAME_MIN_LENGTH: 2,
  NAME_MAX_LENGTH: 100,
  PHONE_MIN_LENGTH: 6,
  PHONE_MAX_LENGTH: 20,
  ADDRESS_MAX_LENGTH: 250,
} as const;